name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: spotdemo4/nix-init@404b7e941df54f8cde2a4efb20c2affa819af909 # v1.30.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: release

      - name: Publish to GitHub
        run: flake-release
        env:
          BUNDLE: appimage
          GITHUB_TOKEN: ${{ steps.checkout.outputs.token }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Docker
        run: flake-release
        env:
          REGISTRY: docker.io
          REGISTRY_USERNAME: ${{ vars.DOCKER_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@71f57208810a5d299fc6545350981de98fdbc860 # v6
        with:
          visibility: public

      - name: Publish to PyPI
        run: |
          uv build
          uv publish
